name: Continuous Integration

on:
  pull_request:
    branches-ignore:
      - 'temp/*'

  push:
    branches-ignore:
      - 'temp/*'

  workflow_dispatch:

jobs:
  check_compilation:
    name: Compilation check
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          set -e
  
          if [ -f Makefile ]; then
            echo "Detected Makefile"
            make
  
          elif [ -f CMakeLists.txt ]; then
            echo "Detected CMake project"
            cmake -B build
            cmake --build build
  
          else
            echo "No supported build system found"
            exit 1
          fi

      - name: Check executables
        if: ${{ vars.EXECUTABLES != '' }}
        run: |
          for binary in ${{ vars.EXECUTABLES }}; do
            if [ ! -x "$binary" ]; then
              echo "Missing executable: $binary"
              exit 1
            fi
          done