name: Continuous Integration

on:
  pull_request:
    branches-ignore:
      - 'temp/*'

  push:
    branches-ignore:
      - 'temp/*'

  workflow_dispatch:

jobs:
  check_compilation:
    name: Compilation check
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          set -e
  
          if [ -f Makefile ]; then
            echo "Detected Makefile"
            make 2>&1 | tee build.log
  
          elif [ -f CMakeLists.txt ]; then
            echo "Detected CMake project"
            cmake -B build
            cmake --build build 2>&1 | tee build.log
  
          else
            echo "No supported build system found"
            exit 1
          fi

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Check executables
        if: ${{ vars.EXECUTABLES != '' }}
        continue-on-error: true
        run: |
          for binary in ${{ vars.EXECUTABLES }}; do
            if [ ! -x "$binary" ]; then
              echo "Missing executable: $binary"
              exit 1
            fi
          done

  check_coding_style:
    name: Coding style checking
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check repository for unwanted files
        run: banana-check-repo . 2>&1 | tee check.log

      - name: Annotations
        run: |
          cat check.log | echo
          if [ ! -s check.log ]; then
            exit 0
          fi
          echo "::warning file=src/ftp/main.cpp::A dumb message"
          
          echo "::group::Coding style errors"

          awk '
          /\[Banana\]/ {
            file = $1
            sub(":", "", file)

            level = "info"
            if ($0 ~ /\[Fatal\]/) level="error"
            else if ($0 ~ /\[Major\]/) level="error"
            else if ($0 ~ /\[Minor\]/) level="warning"
            else if ($0 ~ /\[Info\]/) level="notice"

            msg = $0
            sub(/^[^ ]+ warning: /, "", msg)

            printf "::%s file=%s::%s\n", level, file, msg
          }
          ' check.log

          echo "::endgroup::"
          exit 1